export const GET_TEXT = 'TEXT/GET_TEXT';
export const TOGGLE_LOADER = 'TEXT/TOGGLE_LOADER';

export const SET_NUMBER_OF_LETTERS = 'INDICATOR/SET_NUMBER_OF_LETTERS';
export const ADD_MISTAKE = 'INDICATOR/ADD_MISTAKE';
export const RESET_MISTAKES = 'INDICATOR/RESET_MISTAKES';

export const ADD_SPEED = 'INDICATOR/ADD_SPEED';